language: php
notifications:
  email: false
php:
  - 5.3
before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - sudo cp .travis_ads_rsa ~/.ssh/.travis_ads_rsa
  - sudo echo -e "Host github.com\n IdentityFile ~/.ssh/.travis_ads_rsa\n" >>~/.ssh/config
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - echo "CREATE DATABASE travis_ads_test DEFAULT CHARACTER SET utf8" | mysql -uroot -proot
  - cp build.properties.travis build.properties
  - phpenv config-add php.ini
  - sudo apt-get update -qq
  - sudo apt-get install -qq php-pear
  - sudo pear upgrade pear
  - sudo pear channel-discover pear.phing.info
  - sudo pear config-set preferred_state alpha
  - sudo mkdir /tmp/pear/temp
  - sudo chmod -R 777 /tmp/pear/temp
  - pear config-set cache_dir /tmp/pear/temp
  - sudo pear install --onlyreqdeps phing/phing
  - pear channel-discover pear.drush.org 
  - pear install drush/drush-6.0.0
  - sudo chmod -R 777 /usr/share/drush/includes
  - drush --version
script:
  - phing -debug
  - phing -debug ads-install
