language: php
notifications:
  email: false
php:
  - 5.3
before_script:
  - sudo cp travis.ads.rsa ~/.ssh/travis.ads.rsa
  - sudo cp travis.known_hosts ~/.ssh/known_hosts
  - sudo cat /etc/ssh/ssh_config
  - sudo echo -e "Host github.com\n User git\n IdentityFile ~/.ssh/travis.ads.rsa\n StrictHostKeyChecking no\n PasswordAuthentication no\n CheckHostIP no\n BatchMode yes\n" >> ~/.ssh/config
  - sudo cat ~/.ssh/config
  - sudo cat ~/.ssh/known_hosts
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - echo "CREATE DATABASE travis_ads_test DEFAULT CHARACTER SET utf8" | mysql -uroot -proot
  - cp travis.build.properties build.properties
  - phpenv config-add php.ini
  - sudo apt-get update -qq
  - sudo apt-get install -qq php-pear
  - sudo pear upgrade pear
  - sudo pear channel-discover pear.phing.info
  - sudo pear config-set preferred_state alpha
  - sudo chmod -R 777 "/tmp/pear"
  - sudo pear config-set cache_dir "/tmp/pear/temp"
  - sudo pear install --onlyreqdeps phing/phing
  - sudo pear channel-discover pear.drush.org 
  - sudo pear install drush/drush-6.0.0
  - sudo chmod -R 777 /usr/share/php/drush/lib
  - sudo drush --version
env:
  - GIT_TRACE=1 GIT_SSH="/usr/bin/ssh -oStrictHostKeyChecking=no "
script:
  - sudo phing -debug
  - sudo phing -debug ads-install

